### ISSUE TITLE
Can't find torch 

### ISSUE THREAD

**Issue by luckydipper** [Sense-X/Co-DETR#132]
I can't execute the setup.py. 
Even after I used this command, It still happen. 
```
pip install torch 
```

I don't know what to do
```
(Co-DETR-3.7.11) luckydipper@qhrqufucBookAir Co-DETR % pip install .
Processing /Users/luckydipper/Desktop/drone_following/Co-DETR
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/luckydipper/.pyenv/versions/3.7.11/envs/CO-DETR-3.7.11/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/luckydipper/.pyenv/versions/3.7.11/envs/CO-DETR-3.7.11/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/luckydipper/.pyenv/versions/3.7.11/envs/CO-DETR-3.7.11/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/_3/5ndbtkqj2bgc08vfvfyv3qt00000gn/T/pip-build-env-r143qeo0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/_3/5ndbtkqj2bgc08vfvfyv3qt00000gn/T/pip-build-env-r143qeo0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_3/5ndbtkqj2bgc08vfvfyv3qt00000gn/T/pip-build-env-r143qeo0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/_3/5ndbtkqj2bgc08vfvfyv3qt00000gn/T/pip-build-env-r143qeo0/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by TempleX98** [comment]
Sorry for the late reply. The version of the torch we use is `1.8.1+cuda112_cudnn8.1.0`.
