### ISSUE TITLE
ModuleNotFoundError: No module named 'projects'

### ISSUE THREAD

**Issue by Xiiyuu** [Sense-X/Co-DETR#135]
本地化配置过程中遇到报错ModuleNotFoundError: No module named 'projects'
不知应该如何解决？

**Comment by TempleX98** [comment]
可以先试试把目前的mmdet卸载，然后再在co-detr的仓库pip install安装mmdet

**Comment by DAVID-Hown** [comment]
@TempleX98 仓库里的mmdet文件夹目录也要删除吗

**Comment by DAVID-Hown** [comment]
![image](https://github.com/Sense-X/Co-DETR/assets/55193099/a4ec9f2b-1959-4ddd-8c29-5452775027a9)
@TempleX98

**Comment by DAVID-Hown** [comment]
(base) #: bash tools/dist_train.sh projects/configs/co_dino/co_dino_5scale_vit_large_coco.py 2 path_to_exp
tools/..:
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 24, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 24, in <module>
    from projects import *
ModuleNotFoundError: No module named 'projects'
    from projects import *
ModuleNotFoundError: No module named 'projects'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31459) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-07_08:17:15
  host      : feijian-1-66948bc9f-lprlh
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 31460)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-07_08:17:15
  host      : feijian-1-66948bc9f-lprlh
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31459)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by DAVID-Hown** [comment]
@TempleX98 作者您好 我删掉了mmdet文件夹 但是仍然找不到projects

**Comment by liuzhibin55** [comment]
> 本地化配置过程中遇到报错ModuleNotFoundError: No module named 'projects' 不知应该如何解决？

CSDN博客
https://blog.csdn.net/m0_52695557/article/details/140051810?ops_request_misc=&request_id=&biz_id=102&utm_term=co-detr%20%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-1-140051810.142^v100^pc_search_result_base3&spm=1018.2226.3001.4187

**Comment by dashuai180** [comment]
> 本地化配置过程中遇到报错ModuleNotFoundError: No module named 'projects' 不知应该如何解决？

你好，我遇见了同样的问题，请问您是怎么解决的
