### ISSUE TITLE
test问题

### ISSUE THREAD

**Issue by Jeffzvz** [Sense-X/Co-DETR#156]
:~/github_clone/Co-DETR$ sh tools/dist_test.sh  projects/configs/co_dino/co_dino_5scale_swin_large_3x_coco.py  co_dino_5scale_swin_large_3x_coco.pth  2 --eval bbox
: not foundtest.sh: 5: 
: not foundtest.sh: 6: 
/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
': [Errno 2] No such file or directoryython: can't open file '
': [Errno 2] No such file or directoryython: can't open file '
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 3607330) of binary: /data0/zhm/anaconda3/envs/codetr/bin/python
Traceback (most recent call last):
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data0/zhm/anaconda3/envs/codetr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
 FAILED

**Comment by shuishiwojiade** [comment]
请问最后怎么解决的啊，我也遇到同样的问题
