### ISSUE TITLE
fp16 setting

### ISSUE THREAD

**Issue by hbl843449791** [Sense-X/Co-DETR#159]
Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 241, in main
    meta=meta)
  File "/mnt/data/Co-DETR/tools/mmdet/apis/train.py", line 187, in train_detector
    elif distributed and 'type' not in cfg.optimizer_config:
  File "/mnt/data/miniconda/envs/co-detr/lib/python3.7/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/mnt/data/miniconda/envs/co-detr/lib/python3.7/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer_config'

**Comment by hbl843449791** [comment]
似乎是配置文件中没有设置optimizer_config导致的

**Comment by TempleX98** [comment]
This repository does not support fp16 training.

**Comment by hbl843449791** [comment]
> This repository does not support fp16 training.

mmdet.apis.train.py的182行
`# fp16 setting
    fp16_cfg = cfg.get('fp16', None)
    if fp16_cfg is not None:
        optimizer_config = Fp16OptimizerHook(
            **cfg.optimizer_config, **fp16_cfg, distributed=distributed)
    elif distributed and 'type' not in cfg.optimizer_config:
        optimizer_config = OptimizerHook(**cfg.optimizer_config)
    else:
        optimizer_config = cfg.optimizer_config`
但是配置文件里面只有optimizer，没有optimizer_config，所以报的这个错
