### ISSUE TITLE
推理时报错Not implemented

### ISSUE THREAD

**Issue by hbl843449791** [Sense-X/Co-DETR#160]
推理代码
```
from mmdet.apis import init_detector, inference_detector
import mmcv

# 指定模型的配置文件和 checkpoint 文件路径
config_file = 'projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_rdd.py'
checkpoint_file = 'work_dir/epoch_12.pth'

# 根据配置文件和 checkpoint 文件构建模型
model = init_detector(config_file, checkpoint_file, device='cpu')

# 测试单张图片并展示结果
img = 'test1_images/MotorBike_001977.jpg'  # 或者 img = mmcv.imread(img)，这样图片仅会被读一次
result = inference_detector(model, img)

# 或者将可视化结果保存为图片
model.show_result(img, result, out_file='result.jpg')
```

在result=inference_detector(model,img)这一步报错

Traceback (most recent call last):
  File "demo/image_demo.py", line 69, in <module>
    main(args)
  File "demo/image_demo.py", line 37, in main
    result = inference_detector(model, args.img)
  File "/data/hebailin/Co-DETR/mmdet/apis/inference.py", line 152, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/data/hebailin/miniconda3/envs/co-detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/hebailin/miniconda3/envs/co-detr/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/data/hebailin/Co-DETR/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/data/hebailin/Co-DETR/mmdet/models/detectors/base.py", line 154, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/data/hebailin/Co-DETR/projects/models/co_detr.py", line 541, in aug_test
    feats, img_metas, rescale=rescale)
  File "/data/hebailin/Co-DETR/mmdet/models/dense_heads/anchor_free_head.py", line 350, in aug_test
    return self.aug_test_bboxes(feats, img_metas, rescale=rescale)
  File "/data/hebailin/Co-DETR/projects/models/co_deformable_detr_head.py", line 1077, in aug_test_bboxes
    raise ValueError('Not implemented')
ValueError: Not implemented

**Comment by TempleX98** [comment]
检查一下config里是不是使用了multi-scale test (TTA)

**Comment by hbl843449791** [comment]
config用的就是原来的co_deformable_detr_r50_1x_coco.py，我只把数据改成了我自己的数据

**Comment by TempleX98** [comment]
可以在这里发一下，我看看是什么问题

**Comment by hbl843449791** [comment]
> 可以在这里发一下，我看看是什么问题

解决了，dataset的设置中test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale = (640, 640),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]  
把flip的值设置成False就好了
