### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1428) of binary: /opt/conda/bin/python

### ISSUE THREAD

**Issue by zcqacqwc** [Sense-X/Co-DETR#177]
I’m experiencing an issue. I’ve set up the environment and configured the dataset correctly, but when I run the code, this error appears. How can I resolve it

root@2700da6f9136:/style/Co-DETR# bash tools/dist_train.sh
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    from projects import *
  File "/style/Co-DETR/projects/__init__.py", line 1, in <module>
    from .models import *
  File "/style/Co-DETR/projects/models/__init__.py", line 1, in <module>
    from .co_detr import *
  File "/style/Co-DETR/projects/models/co_detr.py", line 10, in <module>
    from mmdet.models.losses.cross_entropy_loss import generate_block_target
ImportError: cannot import name 'generate_block_target' from 'mmdet.models.losses.cross_entropy_loss' (/opt/conda/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py)
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    from projects import *
  File "/style/Co-DETR/projects/__init__.py", line 1, in <module>
    from .models import *
  File "/style/Co-DETR/projects/models/__init__.py", line 1, in <module>
    from .co_detr import *
  File "/style/Co-DETR/projects/models/co_detr.py", line 10, in <module>
    from mmdet.models.losses.cross_entropy_loss import generate_block_target
ImportError: cannot import name 'generate_block_target' from 'mmdet.models.losses.cross_entropy_loss' (/opt/conda/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py)
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    from projects import *
  File "/style/Co-DETR/projects/__init__.py", line 1, in <module>
    from .models import *
  File "/style/Co-DETR/projects/models/__init__.py", line 1, in <module>
    from .co_detr import *
  File "/style/Co-DETR/projects/models/co_detr.py", line 10, in <module>
    from mmdet.models.losses.cross_entropy_loss import generate_block_target
ImportError: cannot import name 'generate_block_target' from 'mmdet.models.losses.cross_entropy_loss' (/opt/conda/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1428) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-25_12:00:25
  host      : 2700da6f9136
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1429)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-25_12:00:25
  host      : 2700da6f9136
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1430)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-25_12:00:25
  host      : 2700da6f9136
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1428)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by TempleX98** [comment]
Please check the file `mmdet/models/losses/cross_entropy_loss.py` in your environment's mmdetection package. Is this file the same as [the implementation](https://github.com/Sense-X/Co-DETR/blob/28a60116d9bcdd22a876a358b160a27efee785ec/mmdet/models/losses/cross_entropy_loss.py) of this repo?

**Comment by xinyuestudent** [comment]
> Yes, that's correct. The file mmdet/models/losses/cross_entropy_loss.py exists. However, I am encountering the following error:
> 
> ImportError: cannot import name 'generate_block_target' from 'mmdet.models.losses.cross_entropy_loss' (/opt/conda/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py).
> 
> How can I resolve this issue?

I'm running into the same error—any idea how to fix it?

**Comment by adjawdka** [comment]
Have you solved it yet? I got an error during the testing after completing one round of training
`2025-01-03 23:35:19,251 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/home/Co-DETR-main/tools/train.py", line 245, in <module>
    main()
  File "/home/Co-DETR-main/tools/train.py", line 234, in main
    train_detector(
  File "/home/Co-DETR-main/mmdet/apis/train.py", line 245, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/anaconda3/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/anaconda3/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/Co-DETR-main/mmdet/core/evaluation/eval_hooks.py", line 126, in _do_evaluate
    results = multi_gpu_test(
  File "/home/Co-DETR-main/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/Co-DETR-main/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/Co-DETR-main/mmdet/models/detectors/base.py", line 137, in forward_test
    img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
TypeError: 'DataContainer' object is not subscriptable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2163076) of binary: /home/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-03_23:35:29
  host      : MS-7E06
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2163076)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`
