### ISSUE TITLE
bulid_dataset error

### ISSUE THREAD

**Issue by lhl2xju** [Sense-X/Co-DETR#20]
Hello, I encountered this issue during training, indicating that the data class does not have this attribute：

Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 219, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/xxxxxx/Co-DETR/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = MultiImageMixDataset(**cp_cfg)
TypeError: __init__() got an unexpected keyword argument 'ann_file'

**Comment by TempleX98** [comment]
I have fixed it
