### ISSUE TITLE
计算flops

### ISSUE THREAD

**Issue by shuaixinxin** [Sense-X/Co-DETR#40]
您好！我在训练完成后，想要测试模型的flops 使用tools/analysis_tools/get_flops.py进行计算，其中parser.add_argument('--config', default="D:/YOLO/Co-DETR-main/work_dirs/co_deformable_detr_r50_1x_coco/co_deformable_detr_r50_1x_coco.py", help='train config file path')。运行后报错：f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CoDETR is not in the models registry'         请问是哪里出错了呢？望解答，万分感激

**Comment by TempleX98** [comment]
Add this line to `get_flops.py`
`from projects import *`

**Comment by shuaixinxin** [comment]
可是又有了新的问题，原谅我是个cv新手...
C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\mmcv\cnn\utils\flops_counter.py:535: UserWarning: variables __flops__ or __params__ are already defined for the moduleReLU ptflops can affect your code!
  ' ptflops can affect your code!')
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 98, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 83, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\mmcv\cnn\utils\flops_counter.py", line 105, in get_model_complexity_info
    _ = flops_model(batch)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\torch\nn\modules\module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\mmdet-2.25.3-py3.7.egg\projects\models\co_detr.py", line 116, in forward_dummy
    outs = self.bbox_head(x)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\torch\nn\modules\module.py", line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError
请问有没有关于get_flop.py 和benchmark.py计算flop 和FPS 的相关教程呢？

**Comment by TempleX98** [comment]
我已经更新了`forward_dummy`，你可以再试一下。不过不推荐使用mmdet的flops计算工具来计算Co-DETR的flops，因为某些操作比如Deformable Attention不会被统计。
