### ISSUE TITLE
pytorch2onnx with_mask

### ISSUE THREAD

**Issue by bluceliuljx** [Sense-X/Co-DETR#43]
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 337, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 72, in pytorch2onnx
    if model.with_mask:
  File "/root/soft_file/anaconda3/envs/co_detr0904/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'CoDETR' object has no attribute 'with_mask'

**Comment by TempleX98** [comment]
I have implemented `with_mask` in the latest commit

**Comment by Belinda-great** [comment]
> 

Hi I used the latest code with

**Comment by TempleX98** [comment]
@bluceliuljx @Belinda-great, Hi, thanks for your interest in our work! I am sorry that there are some unsolved model export issues. Our repo is implemented using an older version of mmdet (v2.25), which no longer maintains the feature of model export. Co-DETR has been recently incorporated into the official [mmdet v3.x repo](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/projects/CO-DETR), and you can use this official implementation as well as MMDeploy for model export.

**Comment by Belinda-great** [comment]
> 

Thank you for your reply! I will try it. 
And your contributions,  I retrain my datasets(people and head detection), the results were surprisingly good!
So I want to know the speed using ncnn or others.
