### ISSUE TITLE
Issue with Environment (mmdet)

### ISSUE THREAD

**Issue by FrancoisPorcher** [Sense-X/Co-DETR#76]
Dear Co-DETR team, 

I have the following issue with "mmdet":

I ran this command:

bash tools/dist_test.sh  projects/configs/co_deformable_detr/co_dino_5scale_vit_large_lvis.py /private/home/francoisporcher/WeakSupSeg/francois-semi-supervised/Co-DETR/checkpoints/co_dino_5scale_vit_large_lvis.pth 2 --eval bbox

And get the following error:

<img width="1202" alt="image" src="https://github.com/Sense-X/Co-DETR/assets/93766133/8775e9ba-41bc-48b1-b6d2-6965993d2d96">

Could you please explain what environment you use and how you set it up?

The commands I used are:

conda create --name codetr python=3.10 -y; 
conda activate codetr; 
conda install -y pytorch=1.11.0 torchvision torchaudio cudatoolkit=11.5 -c pytorch -c nvidia
pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

I did not install mmdet myself, as you advised, but it seems that it does not work for me.

Thanks!!

**Comment by FrancoisPorcher** [comment]
Also pip install terminal tables does not solve the issue because then there are other libraries (pycocotools, six, etc..)

**Comment by TempleX98** [comment]
Please try pip install -r requirements.txt

**Comment by FrancoisPorcher** [comment]
It does not work..

I still get the error:




The sequence of commands I ran is:

conda create --name codetr python=3.10 -y; conda activate codetr; conda install -y pytorch=1.11.0 torchvision torchaudio cudatoolkit=11.5 -c pytorch -c nvidia


# Then install the requirements
pip install -r requirements.txt

pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

Then:

bash tools/dist_test.sh  projects/configs/co_deformable_detr/co_dino_5scale_vit_large_lvis.py /private/home/francoisporcher/WeakSupSeg/francois-semi-supervised/Co-DETR/checkpoints/co_dino_5scale_vit_large_lvis.pth 2 --eval bbox



And then I get this error:


Traceback (most recent call last):
Traceback (most recent call last):
  File "/private/home/francoisporcher/WeakSupSeg/francois-semi-supervised/Co-DETR/tools/test.py", line 15, in <module>
  File "/private/home/francoisporcher/WeakSupSeg/francois-semi-supervised/Co-DETR/tools/test.py", line 15, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
ModuleNotFoundError    : from mmdet.apis import multi_gpu_test, single_gpu_testNo module named 'mmdet'

ModuleNotFoundError: No module named 'mmdet'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3714025) of binary: /private/home/francoisporcher/anaconda3/envs/codetr/bin/python
tools/dist_test.sh: line 15: 3713949 Segmentation fault      (core dumped) /private/home/francoisporcher/anaconda3/envs/codetr/bin/python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT $(dirname "$0")/test.py $CONFIG $CHECKPOINT --launcher pytorch ${@:4}
(

**Comment by TempleX98** [comment]
I have never met this issue. Maybe you can install mmdet by `pip install -v -e .` to see if it works.

**Comment by FrancoisPorcher** [comment]
So I tried these commands (all ran from the Co-DETR/ folder, right?):

conda create --name codetr python=3.10 -y; conda activate codetr; conda install -y pytorch=1.11.0 torchvision torchaudio cudatoolkit=11.5 -c pytorch -c nvidia

# Then install the requirements
pip install -r requirements.txt

pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

pip install -v -e .

And I get this error:

<img width="1241" alt="image" src="https://github.com/Sense-X/Co-DETR/assets/93766133/815cd532-b61f-4f66-bee0-b71a2b5b1a24">


I tried pip install fair scale, but then its the library fvcore (also called by mmdet), which leads me to think that its mmdet the problem but I am not sure. What do you think?

If it's not too much to ask, could you please try to create the same virtual environment on conda to check? Thanks!

**Comment by Code-of-Liujie** [comment]
The same question, speechless

**Comment by Code-of-Liujie** [comment]
![image](https://github.com/Sense-X/Co-DETR/assets/156080390/a67f504c-c55e-4ee6-8044-5b2e9f9e15d3)
The bug cannot be solved at all. What is the reason that delays my day?

**Comment by MihaiDavid05** [comment]
Hello, @Code-of-Liujie, @FrancoisPorcher . 

I was able to make it work. 
1. git clone https://github.com/Sense-X/Co-DETR.git
2. conda create --name codetr python=3.8 -y
3. conda activate codetr
4. pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 (**mandatory to install it with pip**)
5. pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
6. pip install -r requirements.txt
7. pip install yapf==0.40.1  (this is beacuse of this [error](https://github.com/open-mmlab/mmdetection/issues/10962))

However, I was not able to make the distributed training work :( The training simply gets stuck, and I try almost everything from this [thread](https://github.com/open-mmlab/mmdetection/issues/6534).
