### ISSUE TITLE
TypeError: init_process_group() got an unexpected keyword argument 'port'

### ISSUE THREAD

**Issue by ibarbecue** [Sense-X/Co-DETR#92]
root@d39f6669ec8f:/data1/home/jiangying/BigModel/Co-DETR-main# bash tools/dist_test.sh  projects/configs/co_dino/co_dino_5scale_vit_large_lvis.py checkpoints/co_dino_5scale_vit_large_lvis.pth 1 --eval bbox/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
projects/configs/co_dino/co_dino_5scale_vit_large_lvis.py
Traceback (most recent call last):
  File "tools/test.py", line 276, in <module>
    main()
  File "tools/test.py", line 186, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 40, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 63, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
TypeError: init_process_group() got an unexpected keyword argument 'port'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2977) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-19_18:18:37
  host      : d39f6669ec8f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2977)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by heyitsguay** [comment]
I'm also seeing this error trying to test the ViT-L LVIS model.

**Comment by matt-guay-percipient** [comment]
@ibarbecue I was able to get _dist\_test.sh_ to run successfully by modifying line 305 in _co\_dino\_5scale\_vit\_large\_lvis.py_ from `dist_params = dict(backend='nccl', port=29515)` to `dist_params = dict(backend='nccl')`

**Comment by heyitsguay** [comment]
@ibarbecue I was able to get dist_test.sh to run successfully by modifying line 305 in co_dino_5scale_vit_large_lvis.py from dist_params = dict(backend='nccl', port=29515) to dist_params = dict(backend='nccl')
